server:
 servlet:
  context-path: /cartorgon
 port: 8080
 
info:
 application:
  name: datarest-spring-boot-expl
  description: Spring Data Rest demo project
  type: Spring Boot 2 Data Rest MicroService
  version: 0.0.1-SNAPSHOT
 developers:
  - author:     
     name: Carlos Torres
     email: carlos.a.torres-gonzalez@capgemini.com
     role: Architect
  - author:     
     name: Carlos Torres
     email: carlos.a.torres-gonzalez@capgemini.com
     role: Backend developer
 contributors:
  - author:     
     name: Carlos Torres
     email: carlos.a.torres-gonzalez@capgemini.com
     role: Tester

management:
 endpoint:
  shutdown:
   enabled: true
 endpoints:
  beans:
   enabled: false
  web:
   base-path: /actuator
   exposure:
    include: '*'
    exclude: loggers
 security:
  enabled: false

spring:
 application:
  name: datarest-spring-boot-expl  
 jmx:
  default-domain: datarest.spring.boot.expl 
 
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
  
 jpa:
  open-in-view: false
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
   ddl-auto: update